name: CI

on: [push]

jobs:
  lint_isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Укажите версию Python, которую вы используете

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort

      - name: Run isort
        run: isort . --check --diff

  lint_flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Укажите версию Python, которую вы используете

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 .

  lint_black:
    runs-on: ubuntu-latest
    needs: [lint_isort]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Укажите версию Python, которую вы используете

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: black . --check
