name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Укажите версию Python, которую вы используете

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit  # Установка pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files  # Запуск всех хуков pre-commit